#!/bin/sh

AIRCONNECT_USER="$(echo "${SYNOPKG_PKGNAME}" | awk '{print tolower($_)}')"
LOG="/var/log/${AIRCONNECT_USER}.log"
if [ ! -e "${LOG}" ]; then
    touch "${LOG}"
fi

echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Start postuninst... ####" >>"$LOG"
echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Done postuninst ####" >>"$LOG"
exit 0
