#!/bin/sh

AIRCONNECT_USER="$(echo "${SYNOPKG_PKGNAME}" | awk '{print tolower($_)}')"
LOG="/var/log/${AIRCONNECT_USER}.log"
if [ ! -e "${LOG}" ]; then
    touch "${LOG}"
fi

echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Start preinst... ####" >>"$LOG"
# Ensure user 'airconnect' exists before doing anything
if ! synouser --get "${AIRCONNECT_USER}" >/dev/null 2>&1; then
    # create user with random password
    echo "[$(date +'%T')] Creating \"${AIRCONNECT_USER}\" user." >>"$LOG"
    synouser --add "${AIRCONNECT_USER}" "$(uuidgen | cut -c-8)" 'AirConnect User' 0 '' ''
else
    echo "[$(date +'%T')] Securing existing \"${AIRCONNECT_USER}\" user." >>"$LOG"
    synouser --modify "${AIRCONNECT_USER}" 'AirConnect User' 0 ''
fi
sleep 3
echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Done preinst ####" >>"$LOG"
exit 0
