#!/bin/sh

AIRCONNECT_USER="$(echo "${SYNOPKG_PKGNAME}" | awk '{print tolower($_)}')"
LOG="${SYNOPKG_PKGDEST}/${AIRCONNECT_USER}.log"
if [ ! -e "${LOG}" ]; then
    touch "${LOG}"
fi

echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Start preinst... ####" >>"$LOG"
echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Done preinst ####" >>"$LOG"
exit 0
