#!/bin/sh

AIRCONNECT_USER="$(echo "${SYNOPKG_PKGNAME}" | awk '{print tolower($_)}')"
LOG="/var/log/${AIRCONNECT_USER}.log"
if [ ! -e "${LOG}" ]; then
    touch "${LOG}"
fi

echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Start preuninst... ####" >>"$LOG"
#make sure airconnect is stopped
killall -16 airupnp >/dev/null 2>&1
killall -16 aircast >/dev/null 2>&1
sleep 10

echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Done preuninst ####" >>"$LOG"
exit 0
