name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Shellcheck
      run: make shellcheck

    - name: Test packaging of x86_64
      run: ARCH=x86_64 make build
      
    - name: Test packaging
      run: make build-all
    
    - name: Cleanup target
      run: make clean
    
    - name: Cleanup dist
      run: make clean-dist
